### ISSUE TITLE
What we need fixed in order to ship the first Czech version

### ISSUE THREAD

**Issue by zoul** [theodi/open-data-certificate#1331]
We need to ship the first version of the Czech localization in November. Thanks to the recent effort by @tonymarklove we are moving much faster towards meeting the deadline. These are the issues that we still need fixed in order to ship:

- [x] #1287 Unlocalized strings in the web app interface
- [x] #1330 „This self-assessment questionnaire…“ intro text not getting localized
- [x] #1293 Make static pages localizable. I believe we already have everything we wanted here.
- [x] #1288 Site layout broken by localized strings
- [x] #1274 Certificate level & badge localization. I also think we have what we need, we can change the badge names in Transifex.
- [x] #1332 Can’t edit translations in Transifex after review
- [x] #1334 Certificate data shown in English although the site and jurisdiction are set to Czech

These would be nice to have:

- [x] #1292 Make relative dates localizable
- [x] #1236 Improve pluralization support

Also, what’s the process for moving code from the staging environment to production? Obviously, we need the code running on the production server. Is there a fixed delay in deploying the staging code to production? Or can we simply say when we have everything in place and you will deploy the changes to production immediately?

(CC: @michalkuban)

**Comment by tonymarklove** [comment]
I will continue looking at these non-resolved issues today. I think most of them are done and just need to go up to the staging server., but I'll double check everything.

We can deploy to production whenever we want, there is no fixed delay. Do you have fixed deadlines that we should know about. If we keep the code clear of any big, non-translation features then we can be confident of deploying as the deadlines get closer.

**Comment by zoul** [comment]
Great, thank you. We would love to have the work finished by the November 15th.

**Comment by tonymarklove** [comment]
@zoul I believe all these remaining issues are now resolved on the staging site. There may be a few places where we haven't pulled down the latest Transifex translations, but other than that everything I know about is complete.

There are a few more untranslated strings in Transifex now. Once those are all done we can sync the changes up to staging and do a final check of the whole site.

**Comment by zoul** [comment]
Perfect, thank you. I am working on a PR with the rest of the changes we need merged. Is there an easy way to know which revision is deployed where? (So that we have an idea what change should be visible on staging and production server.)

**Comment by tonymarklove** [comment]
@zoul We tag the whenever a staging or production build is deployed. So one easy way to see that is on the https://github.com/theodi/open-data-certificate/releases page, for example. `STAGING` and `CURRENT` are the ones to look for.

**Comment by zoul** [comment]
D’oh, I could have realized that. Thanks!
