### ISSUE TITLE
Web analytics - improve tracking on the website

### ISSUE THREAD

**Issue by sumikasan** [theodi/open-data-certificate#889]
As a ODC product manager
I want to know whether the user is clicking the link/button
So that I know where to prioritise when making improvements on the site

Basic Requirements:
  - [ ] Can identify which buttons or links on the same page are redundant
  - [x] Can identify how the user is interacting with the survey form
  - [x] Can identify what boxes users are stopping and leaving at
  - [x] Can track the survey form submissions that are actually submitted and not just filled in and abandoned
  - [x] Can track when the window is scrolled down (to see if anyone is reading before the fold)
  - [x] Can track the search terms used on site

Also see #888

**Comment by pkqk** [comment]
Not sure how to track redundant buttons but everything else is putting events into Google Analytics.

I've written a [summary](https://github.com/theodi/open-data-certificate/blob/master/doc/tracking.md) of all the events.
